apps:
- name: client
  script: node_modules/nuxt/bin/nuxt-start
  cwd: /root/build
  max_memory_restart: "250M"
  args: "--max-old-space-size=200"
  env_production:
    PORT: 3000
    NODE_ENV: production

- name: server
  script: app.js
  cwd: /root/server
  env_production:
    PORT: 3001
    NODE_ENV: production
